name: Deploy GitHub Pages

on:
  workflow_dispatch:

jobs:
  generate-openapi-spec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Upload openapi.json
        uses: actions/upload-artifact@v4
        with:
          name: spec-file
          path: openapi.yaml
  deploy:
    needs: generate-openapi-spec
    runs-on: ubuntu-latest
    steps:
      - name: Download openapi.yaml
        uses: actions/download-artifact@v4
        with:
          name: spec-file
      - name: Generate Swagger UI
        uses: Legion2/swagger-ui-action@v1
        with:
          output: swagger-ui
          spec-file: openapi.yaml
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: swagger-ui
