on:
  push:
    branches:
      - main
permissions:
    contents: write
    pull-requests: write
name: release please
jobs:
    release-please:
        runs-on: ubuntu-latest
        steps:
        - uses: google-github-actions/release-please-action@v3
          id: release
          with:
            path: 'release-automation'
            release-type: go
            package-name: release-automation
        - name: tag major and minor versions
          if: ${{ steps.release.outputs.release_created }}
          run: |
            git tag -d v${{ steps.release.outputs.major }} || true
            git tag -d v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
            git push origin :v${{ steps.release.outputs.major }} || true
            git push origin :v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
            git tag -a v${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
            git tag -a v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
            git push origin v${{ steps.release.outputs.major }}
            git push origin v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}